C Included text uses fixed form                                         
      value = 10                                                        
     &+ 11                                                              
      go to 20                                                          
      value = -3                                                        
   20 continue                                                          
