C Leading comment                                                       
                                                                        
      value = 10                                                        
     &+ 2                                                               
C Trailing comment                                                      
                                                                        
